const express=require('express');const path=require('path');const session=require('express-session');const QRCode=require('qrcode');const connectDB=require('./db');const Drive=require('./models/Drive');const Participant=require('./models/Participant');
const app=express();const port=process.env.PORT||8080;connectDB();
app.set('view engine','ejs');app.set('views',path.join(__dirname,'views'));app.use(express.static(path.join(__dirname,'public')));app.use(express.urlencoded({extended:true}));app.use(express.json());app.use(session({secret:process.env.SESSION_SECRET||'pulsereach-prototype',resave:false,saveUninitialized:true}));
function score(p){let s=45;if(p.confirmationStatus==='Confirmed')s+=28;if(p.confirmationStatus==='Declined')s-=25;s+=Math.min(15,(p.reminderEngagement||0)*5);s+=p.responseScore||0;if(p.previousParticipation)s+=8;return Math.max(5,Math.min(97,s));}
async function seed(){if(await Drive.countDocuments()===0){const d=await Drive.create({name:'GCOEA Mega Blood Donation Drive',date:new Date('2026-09-25T10:00:00+05:30'),venue:'GCOEA Campus',targetCount:300,screeningLink:'https://example.org/screening',description:'Community blood donation drive coordinated with authorised medical professionals.'});const names=['Aarav Patil','Riya Deshmukh','Aditya Joshi','Sneha Kulkarni','Vedant Sharma','Ananya More','Om Wankhede'];await Participant.insertMany(names.map((name,i)=>{const p={driveId:d._id,name,phone:`98${String(10000000+i)}`,email:'',preferredLanguage:['English','Marathi','Hindi'][i%3],communicationConsent:i!==6,futureDriveConsent:i%2===0,confirmationStatus:i<4?'Confirmed':'Pending',reminderEngagement:i%4,previousParticipation:i%3===0,responseScore:i%3};p.predictedAttendance=score(p);return p;}));}}
app.get('/',(req,res)=>res.render('landing'));app.get('/dashboard',async(req,res)=>{const drives=await Drive.find().sort({createdAt:-1});const participants=await Participant.find().sort({createdAt:-1});participants.forEach(p=>{p.predictedAttendance=score(p)});const total=participants.length,confirmed=participants.filter(p=>p.confirmationStatus==='Confirmed').length,attended=participants.filter(p=>p.attendanceStatus==='Attended').length,predicted=total?Math.round(participants.reduce((a,p)=>a+p.predictedAttendance,0)/100*total):0;res.render('dashboard',{drives:drives.map(d=>({...d.toObject(),predicted:Math.min(99,Math.round((participants.filter(p=>String(p.driveId)===String(d._id)).reduce((a,p)=>a+p.predictedAttendance,0)||0)/(participants.filter(p=>String(p.driveId)===String(d._id)).length||1)))})),participants,stats:{total,confirmed,predicted,attended},consentRate:total?Math.round(participants.filter(p=>p.communicationConsent).length/total*100):0,confirmedRate:total?Math.round(confirmed/total*100):0,engagedRate:total?Math.round(participants.filter(p=>p.reminderEngagement>0).length/total*100):0});});
app.get('/drives/new',(req,res)=>res.render('new-drive'));app.post('/drives',async(req,res)=>{const d=await Drive.create({name:req.body.name,date:req.body.date,venue:req.body.venue,targetCount:req.body.targetCount,screeningLink:req.body.screeningLink,description:req.body.description});res.redirect(`/drives/${d._id}`)});
app.get('/drives/:id',async(req,res)=>{
  const d=await Drive.findById(req.params.id);
  if(!d)return res.status(404).send('Drive not found');
  const url=req.protocol+'://'+req.get('host')+'/register/'+d._id;
  const qr=await QRCode.toDataURL(url);
  const participants=await Participant.find({driveId:d._id});
  res.render('drive-detail',{drive:d,url,qr,participantCount:participants.length});
});
app.get('/register/demo',async(req,res)=>{let d=await Drive.findOne().sort({createdAt:-1});if(!d){await seed();d=await Drive.findOne()}res.redirect(`/register/${d._id}`)});app.get('/register/:id',async(req,res)=>{const d=await Drive.findById(req.params.id);if(!d)return res.status(404).send('Drive not found');res.render('register',{drive:d})});app.post('/register/:id',async(req,res)=>{const d=await Drive.findById(req.params.id);if(!d)return res.status(404).send('Drive not found');const p=await Participant.create({driveId:d._id,name:req.body.name,phone:req.body.phone,email:req.body.email,preferredLanguage:req.body.preferredLanguage,communicationConsent:req.body.communicationConsent==='on',futureDriveConsent:req.body.futureDriveConsent==='on'});p.predictedAttendance=score(p);await p.save();res.render('success',{drive:d,participant:p})});
app.get('/participants',async(req,res)=>{const p=await Participant.find().populate('driveId').sort({createdAt:-1});res.json(p.map(x=>({...x.toObject(),predictedAttendance:score(x)})))});
app.post('/api/participants/:id/confirm',async(req,res)=>{const p=await Participant.findByIdAndUpdate(req.params.id,{confirmationStatus:req.body.status||'Confirmed'},{new:true});if(!p)return res.status(404).json({message:'Participant not found'});p.predictedAttendance=score(p);await p.save();res.json({success:true,participant:p})});app.post('/api/participants/:id/attendance',async(req,res)=>{const p=await Participant.findByIdAndUpdate(req.params.id,{attendanceStatus:req.body.status||'Attended'},{new:true});if(!p)return res.status(404).json({message:'Participant not found'});res.json({success:true,participant:p})});
seed().then(()=>app.listen(port,()=>console.log(`PulseReach running on http://localhost:${port}`)));
